- name: "Checking for Distribution Config for distribution: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Running tasks for distribution: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Zshrc | Create symlink to .Zshrc file"
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ ansible_distribution }}/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    state: link
    force: true

