- name: Check if mise is installed
  ansible.builtin.command: which mise
  register: mise_check
  changed_when: false
  ignore_errors: true

- name: Install mise
  ansible.builtin.shell: |
    curl https://mise.run | sh
  when: mise_check.rc != 0
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/mise"
