- name: "Checking for Distribution Config for distribution: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Running tasks for distribution: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Git | Create symlink to .gitconfig file"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.gitconfig"
    dest: "{{ ansible_user_dir }}/.gitconfig"
    state: link
    force: true

- name: "Git | Create Work folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/Developer/VELUX"
    state: directory

- name: "Git | Create symlink to work .gitconfig"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.gitconfig_work"
    dest: "{{ ansible_user_dir }}/Developer/VELUX/.gitconfig"
    state: link
    force: true
