- name: "Checking for Distribution Config for distribution: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Running tasks for distribution: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    update: true

- name: "Tmux | Config folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

- name: "Tmux | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_user_dir }}/.config/tmux"
    state: link
    force: true
