---
- name: Bootstrap dotfiles
  hosts: local

  tasks:
    - name: Gather all roles in the roles directory
      ansible.builtin.find:
        paths: "~/dotfiles/ansible/roles" # Adjust the path if your roles are elsewhere
        file_type: directory
        depth: 1
      register: roles_directory
      tags:
        - always

    - name: Set roles to run
      ansible.builtin.set_fact:
        run_roles: "{{ roles_directory.files | map(attribute='path') | map('basename') | list }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      loop: "{{ run_roles }}"
      tags:
        - always
