---
- name: "Neovim | MacOSX | Dependencies"
  community.general.homebrew:
    name:
      - ripgrep
    state: present

- name: "Neovim | MacOSX | Install"
  community.general.homebrew:
    name: neovim
    state: present
